### ISSUE TITLE
Broken links to the demo

### ISSUE THREAD

**Issue by Zhouzi** [nodes777/flower-game-phaser3#280]
Hey! I stumbled upon your article [Creating an Isometric View in Phaser 3](https://tnodes.medium.com/creating-an-isometric-view-in-phaser-3-fada95927835) and was unable to access the demo from there as the link is broken. The link in the GitHub repository's description is also broken.

The one in the readme does work, though: http://www.spacegarden.xyz/

Kudos for the article, it's the most up to date I found so far 🙌

**Comment by nodes777** [comment]
Hey thanks for the catch! I have updated those links. Thanks for the kind words too!
